# Generated by Django 5.0.6 on 2024-08-22 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('vaga_interesse', models.CharField(blank=True, max_length=255, null=True)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])])),
                ('observacoes', models.TextField(blank=True)),
                ('processo_selecao', models.CharField(choices=[('entrevistado', 'Entrevistado'), ('aguardando_entrevista', 'Aguardando Entrevista')], max_length=21)),
                ('resultado', models.CharField(blank=True, choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('futura', 'Vaga Futura')], max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, default='static/images/default-avatar-new.png', null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
